services:
  mysql:
    image: mysql:8.0
    container_name: mysql_loterie
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loterie
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  # ‚Üê IMPORTANT

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_loterie
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql